In [11]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path().resolve()

while not (BASE_DIR / "data").exists():
    BASE_DIR = BASE_DIR.parent

DATA_PATH = BASE_DIR / "data" / "CASE_Vaga_SR.csv"

if not DATA_PATH.exists():
    raise FileNotFoundError(f"Arquivo não encontrado: {DATA_PATH}")

df = pd.read_csv(DATA_PATH, low_memory=False)
df

,mes_ref,data_competencia,status_ordem_venda,canal_1,cpf_cnpj,cliente_filho,empresa,fabrica,codigo_setor_atividade,codigo_produto,produto,Receita_faturada,Volume_faturado,Receita_vendida,Volume_vendido
0,2025-01-01,2025-01-08,FATURAMENTO,LOES,1.508984e+13,MONET IMPORTACAO E COMERCIO LTDA,DECA,METAIS,MS,1198.BL.TUB.TET.MT,TORNEIRA DE TETO TUBE -BL MT,4230.77,1.0,0.00,0.0
1,2025-04-01,2025-04-16,FATURAMENTO,LOES,5.192514e+13,CONDEC MATERIAL DE CONSTRUCAO LTDA,DECA,LOUÇAS,LS,P.23.26,BACIA CONVENCIONAL LK - BARBANTE,6251.27,5.0,0.00,0.0
2,2025-06-01,2025-06-27,FATURAMENTO,VAREJO,6.108249e+13,VILLAGE MATERIAIS DE ACABAMENTO,DECA,METAIS,MS,4509.502,BASE REG DE GAVETA 11/2 DN40-B,443.15,6.0,0.00,0.0
3,2025-03-01,2025-03-26,FATURAMENTO,LOES,3.153370e+13,OGUNJA COM VAREJ DE MAT DE CONST,DECA,LOUÇAS,LS,L.13050.LQ.85,CUBA DE APO RETANG LIQUID 50CM - SFT ANT,1218.39,2.0,0.00,0.0
4,2025-01-01,2025-01-25,FATURAMENTO,VAREJO,3.181914e+13,A.S MATERIAIS DE CONSTRUCAO LTDA,DECA,METAIS,MS,2875.C13,MIST MONO LAV GAMA MESA B BAIXA CR,657.38,2.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2599385,2025-11-01,2025-11-07,DEVOLUÇÃO,VAREJO,1.949660e+12,PEDRAO - DEPOSITO DA CONSTRUCAO,DECA,METAIS,MS,1502.B.100,REG DE GAV USO SEMI-IND 1 DN25-B,-590.64,-12.0,-590.64,-12.0
2599386,2025-11-01,2025-11-18,DEVOLUÇÃO,ENGENHARIA,5.330272e+13,CONDOMINIO CASA SERENA,DECA,LOUÇAS,LS,P.606.22,BACIA P/CAIXA ACOPL CARRARA-MARROM FSC,-1291.38,-1.0,-1291.38,-1.0
2599387,2025-11-01,2025-11-18,DEVOLUÇÃO,VAREJO,9.790210e+11,FERRAGEM ALVORADA LTDA,DECA,LOUÇAS,LS,P.47.94,BACIA CONVENCIONAL AXIS - EBANO FOSCO,-466.54,-1.0,-466.54,-1.0
2599388,2025-03-01,2025-03-17,FATURAMENTO,CAPABILITIES,9.783718e+13,DEXCO S.A,DECA,METAIS,MS,4916.C.112.DUO,KIT CONV HYDRA MAX P/HYDRA DUO 11/2-CR,0.00,0.0,0.00,0.0
2599389,2025-02-01,2025-02-27,FATURAMENTO,ENGENHARIA,6.137986e+13,ATHIE WOHNRATH ASSOCIADOS,DECA,METAIS,MS,4916.C.DSC.PQ,ACAB P/REG PRES 1/2E3/4 PQ DISCO - CR,0.00,0.0,0.00,0.0

In [12]:
# Bibliotecas
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import warnings
warnings.filterwarnings("ignore")

BASE_DIR = Path().resolve()

while not (BASE_DIR / "data").exists():
    BASE_DIR = BASE_DIR.parent

DATA_PATH = BASE_DIR / "data" / "CASE_Vaga_SR.csv"

if not DATA_PATH.exists():
    raise FileNotFoundError(f"Arquivo não encontrado: {DATA_PATH}")

df = pd.read_csv(DATA_PATH, low_memory=False)

# Visualização das Dimensões da base
print(f"\nDimensões do dataset: {df.shape[0]:,} linhas x {df.shape[1]} colunas")
print(f"Colunas: {list(df.columns)}\n")

# Converter datas
df['mes_ref'] = pd.to_datetime(df['mes_ref']).dt.strftime('%d/%m/%Y')
df['data_competencia'] = pd.to_datetime(df['data_competencia']).dt.strftime('%d/%m/%Y')

df

Dimensões do dataset: 2,599,390 linhas x 15 colunas
Colunas: ['mes_ref', 'data_competencia', 'status_ordem_venda', 'canal_1', 'cpf_cnpj', 'cliente_filho', 'empresa', 'fabrica', 'codigo_setor_atividade', 'codigo_produto', 'produto', 'Receita_faturada', 'Volume_faturado', 'Receita_vendida', 'Volume_vendido']

,mes_ref,data_competencia,status_ordem_venda,canal_1,cpf_cnpj,cliente_filho,empresa,fabrica,codigo_setor_atividade,codigo_produto,produto,Receita_faturada,Volume_faturado,Receita_vendida,Volume_vendido
0,01/01/2025,08/01/2025,FATURAMENTO,LOES,1.508984e+13,MONET IMPORTACAO E COMERCIO LTDA,DECA,METAIS,MS,1198.BL.TUB.TET.MT,TORNEIRA DE TETO TUBE -BL MT,4230.77,1.0,0.00,0.0
1,01/04/2025,16/04/2025,FATURAMENTO,LOES,5.192514e+13,CONDEC MATERIAL DE CONSTRUCAO LTDA,DECA,LOUÇAS,LS,P.23.26,BACIA CONVENCIONAL LK - BARBANTE,6251.27,5.0,0.00,0.0
2,01/06/2025,27/06/2025,FATURAMENTO,VAREJO,6.108249e+13,VILLAGE MATERIAIS DE ACABAMENTO,DECA,METAIS,MS,4509.502,BASE REG DE GAVETA 11/2 DN40-B,443.15,6.0,0.00,0.0
3,01/03/2025,26/03/2025,FATURAMENTO,LOES,3.153370e+13,OGUNJA COM VAREJ DE MAT DE CONST,DECA,LOUÇAS,LS,L.13050.LQ.85,CUBA DE APO RETANG LIQUID 50CM - SFT ANT,1218.39,2.0,0.00,0.0
4,01/01/2025,25/01/2025,FATURAMENTO,VAREJO,3.181914e+13,A.S MATERIAIS DE CONSTRUCAO LTDA,DECA,METAIS,MS,2875.C13,MIST MONO LAV GAMA MESA B BAIXA CR,657.38,2.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2599385,01/11/2025,07/11/2025,DEVOLUÇÃO,VAREJO,1.949660e+12,PEDRAO - DEPOSITO DA CONSTRUCAO,DECA,METAIS,MS,1502.B.100,REG DE GAV USO SEMI-IND 1 DN25-B,-590.64,-12.0,-590.64,-12.0
2599386,01/11/2025,18/11/2025,DEVOLUÇÃO,ENGENHARIA,5.330272e+13,CONDOMINIO CASA SERENA,DECA,LOUÇAS,LS,P.606.22,BACIA P/CAIXA ACOPL CARRARA-MARROM FSC,-1291.38,-1.0,-1291.38,-1.0
2599387,01/11/2025,18/11/2025,DEVOLUÇÃO,VAREJO,9.790210e+11,FERRAGEM ALVORADA LTDA,DECA,LOUÇAS,LS,P.47.94,BACIA CONVENCIONAL AXIS - EBANO FOSCO,-466.54,-1.0,-466.54,-1.0
2599388,01/03/2025,17/03/2025,FATURAMENTO,CAPABILITIES,9.783718e+13,DEXCO S.A,DECA,METAIS,MS,4916.C.112.DUO,KIT CONV HYDRA MAX P/HYDRA DUO 11/2-CR,0.00,0.0,0.00,0.0
2599389,01/02/2025,27/02/2025,FATURAMENTO,ENGENHARIA,6.137986e+13,ATHIE WOHNRATH ASSOCIADOS,DECA,METAIS,MS,4916.C.DSC.PQ,ACAB P/REG PRES 1/2E3/4 PQ DISCO - CR,0.00,0.0,0.00,0.0